spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: tripManagementSystem
          uri: lb://tripManagementSystem
          predicates:
            - Path=/trip/**
          filters:
            - AuthenticationFilter
        - id: fleetManagementSystem
          uri: lb://fleetManagementSystem
          predicates:
            - Path=/fleet/**
          filters:
            - AuthenticationFilter
        - id: masterDataManagementSystem
          uri: lb://masterDataManagementSystem
          predicates:
            - Path=/masterData/**
          filters:
            - AuthenticationFilter
        - id: authenticationSystem
          uri: lb://authenticationSystem
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
